# Generated by Django 3.2.8 on 2021-10-21 18:25

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields
import seazone.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Check-In', 'Check-In'), ('Check-Out', 'Check-Out')], default='Check-In', max_length=9)),
                ('codigo_quarto', models.CharField(max_length=6)),
                ('quantidade_de_pessoas', models.IntegerField()),
                ('quantida_de_pets', models.IntegerField()),
                ('quantidade_de_diarias', models.IntegerField()),
                ('valor', models.FloatField()),
                ('horario', models.TimeField(default=datetime.datetime.now)),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8, validators=[seazone.models.only_int])),
                ('codigo_reserva', models.CharField(max_length=10)),
                ('nome_cliente', models.CharField(max_length=50)),
                ('telefone_cliente', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('concluido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Limpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_quarto', models.CharField(max_length=6)),
                ('horario', models.TimeField(default=datetime.datetime.now)),
                ('data_limpeza', models.DateField()),
                ('cidade', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=255)),
                ('rua', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=8, validators=[seazone.models.only_int])),
                ('concluido', models.BooleanField(default=False)),
            ],
        ),
    ]
